config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'static_pages/impressum' 
  root 'static_pages#index' 
  post 'static_pages/mail_sent'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

def mail_sent
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  UserMailer.contact_form(@email, @name, @message).deliver_now
 flash[:notice] = "Ihre Nachricht wurde versendet!"
  redirect_to :back

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frühlingserwachen</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    
    <!-- HERO IMAGE -->
    <div class="container branding">
    		<%= image_tag("logo.png", class: "img-responsive col-md-offset-1 col-md-10 col-xs-12 heroimg") %>
    </div>

    <!-- NAV BAR -->
    <!-- <div class="main-menu container"> -->
      <nav class="wrapper main-menu sticker" role="navigation" id="container-navbar">
        <ul class="menu" id="menu-main">
          <li class="menu-item-1 page-scroll" id="nav-about" ><%= link_to "Was wir wollen", static_pages_index_path(anchor: "about")%></li>
          <li class="menu-item-2 page-scroll" id="nav-blog"><%= link_to "Was gerade los ist", static_pages_index_path(anchor: "blog")%></li>
          <li class="menu-item-3 page-scroll" id="nav-bus"><%= link_to "Frühstücksbus", static_pages_index_path(anchor: "bus")%></li>
          <li class="menu-item-4 page-scroll" id="nav-stimmen"><%= link_to "Stimmen", static_pages_index_path(anchor: "stimmen")%></li>
          <li class="menu-item-5 page-scroll" id="nav-contact"><%= link_to "Kontakt", static_pages_index_path(anchor: "contact")%></li>
          <li class="menu-item-6 page-scroll" id="nav-partner"><%= link_to "Partner", static_pages_index_path(anchor: "partner")%></li>
        </ul>
        <script type="text/javascript">
          $("#menu-main").addClass("js").before('<div id="mobile-menu" class="sticker">&#9776; Menü</div>');
          $("#mobile-menu").click(function(){
            $("#menu-main").toggle();
          });
          $(window).resize(function(){
            if(window.innerWidth > 768) {
              $("#menu-main").removeAttr("style");
            }
          });
        </script>
        
        <!-- SMOOTH SCROLLING -->
<!--         <script type="text/javascript">
          var $root = $('html, body');
$('a').click(function() {
    var href = $.attr(this, 'href');
    $root.animate({
        scrollTop: $(href).offset().top
    }, 500, function () {
        window.location.hash = href;
    });
    return false;
});
        </script> -->
    
      </nav>
    <!-- </div> -->

    <!-- CONTENT -->
    <%= yield %>

<!--     <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
 -->    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  </body>
</html>

app/views/static_pages/impressum.html.erb
<div class="container">
<div class="container2">
<h1>Impressum</h1><br>
<h3>Zeppelin University Frühlingserwachen</h3><br>

<p>Eine Initiative von Studenten der:<br><br>
Zeppelin Universität gemeinnützige GmbH<br>
Am Seemoser Horn 20 D<br>
88045 Friedrichshafen<br>
Tel. +49 7541 6009-0<br>
Fax +49 7541 6009-119<br>
Vertreten durch die Geschäftsführer:<br>
Prof Dr Insa Sjurts (Sprecherin) | Matthias Schmolz<br>
Registergericht: Amtsgericht Ulm<br>
Register-Nr.: HRB 63 2002<br>
USt-Ident-Nr.: DE229010877<br>
Kontakt:<br>
Nils Philippi (Gesamtleitung, Presse)<br>
Luise Kunz (künstlerische Leitung)<br><br></p>


<h3>Disclaimer</h3><br>
<p><b>1. Haftungsbeschränkung</b><br>
Die Inhalte des Internetauftritts wurden mit größtmöglicher Sorgfalt und nach bestem Gewissen erstellt. Dennoch übernimmt der Anbieter dieser Webseite keine Gewähr für die Aktualität, Vollständigkeit und Richtigkeit der bereitgestellten Seiten und Inhalte. Als Diensteanbieter ist der Anbieter dieser Webseite gemäß § 7 Abs. 1 TMG für eigene Inhalte und bereitgestellte Informationen auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich; nach den §§ 8 bis 10 TMG jedoch nicht verpflichtet, die übermittelten oder gespeicherten fremden Informationen zu überwachen. Eine Entfernung oder Sperrung dieser Inhalte erfolgt umgehend ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung. Eine Haftung ist erst ab dem Zeitpunkt der Kenntniserlangung möglich.<br><br>
<b>2. Externe Links</b><br>
Die Webseite enthält sog. „externe Links“ (Verlinkungen) zu anderen Webseiten, auf deren Inhalt der Anbieter der Webseite keinen Einfluss hat. Aus diesem Grund kann der Anbieter für diese Inhalte auch keine Gewähr übernehmen. Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der verlinkten Webseite verantwortlich. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar. Bei Bekanntwerden einer solchen Rechtsverletzung wird der Link umgehend entfernen.<br><br>
<b>3. Urheberrecht/Leistungsschutzrecht</b><br>
Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des jeweiligen Rechteinhabers. Das unerlaubte Kopieren/Speichern der bereitgestellten Informationen auf diesen Webseiten ist nicht gestattet und strafbar.<br><br>
<b>4. Datenschutz</b><br>
Durch den Besuch des Internetauftritts können Informationen (Datum, Uhrzeit, aufgerufene Seite) über den Zugriff auf dem Server gespeichert werden. Es werden keine personenbezogenenen (z. B. Name, Anschrift oder E-Mail-Adresse) Daten, gespeichert. Sofern personenbezogene Daten erhoben werden, erfolgt dies, sofern möglich, nur mit dem vorherigen Einverständnis des Nutzers der Webseite. Eine Weitergabe der Daten an Dritte findet ohne ausdrückliche Zustimmung des Nutzers nicht statt. Der Anbieter weist darauf hin, dass die Übertragung von Daten im Internet (z. B. per E-Mail) Sicherheitslücken aufweisen und ein lückenloser Schutz der Daten vor dem Zugriff Dritter nicht gewährleistet werden kann. Der Anbieter übernimmt keine Haftung für die durch solche Sicherheitslücken entstandenen Schäden. Der Verwendung der Kontaktdaten durch Dritte zur gewerblichen Nutzung wird ausdrücklich widersprochen. Es sei denn, der Anbieter hat zuvor seine schriftliche Einwilligung erteilt. Der Anbieter behält sich rechtliche Schritte für den Fall der unverlangten Zusendung von Werbeinformationen, z. B. durch Spam-Mails, vor.<br>
</p>
</div> <!-- end container2 -->
</div> <!-- end container -->

app/views/static_pages/index.html.erb
<script src="app/assets/javascripts/jquery.stellar.min.js"></script>
<script type="text/javascript">$.stellar();</script>

   <div class="container" id="about">
     <div class="container2">
        <br> <!-- ggf rausnehmen -->
          <h1>Was wir wollen</h1>  <br> <!-- ggf rausnehmen -->
            <div class="row featurette">
                 <div class="col-md-6"><p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. <br><br>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est.</p></div>
                 <div class="col-md-6"><%= image_tag("baum.jpg", class:"featurette-image img-responsive center-block") %></div>
         </div>
         <br><br>
      </div>
    </div>


     <div class="container" id="blog" data-stellar-background-ratio="0.5">
        <div class="container2" id="blog-container" data-stellar-background-ratio="1.8">
             <br><!-- ggf rausnehmen -->
    	<h1>Was gerade los ist</h1>
                <br> <!-- ggf rausnehmen -->
                <div class="row">
                  <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <%= image_tag("logo.png", class: "img-responsive col-md-offset-1 col-md-10 col-xs-12 heroimg") %>
                      <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                        <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <%= image_tag("logo.png", class: "img-responsive col-md-offset-1 col-md-10 col-xs-12 heroimg") %>
                      <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                        <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                    </div>
                  </div>
                  <div class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                      <%= image_tag("logo.png", class: "img-responsive col-md-offset-1 col-md-10 col-xs-12 heroimg") %>
                      <div class="caption">
                        <h3>Thumbnail label</h3>
                        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.</p>
                        <p><a href="#" class="btn btn-default" role="button">Button</a></p>
                      </div>
                    </div>
                  </div>
                </div>
                <br><br> <!-- ggf rausnehmen -->
        </div>
     </div>

     <div class="container" id="bus">
        <div class="container2">
        <br> <!-- ggf rausnehmen -->
    	<h1>Frühstücksbus</h1><!-- frühstücksbus -->
             <br> <!-- ggf rausnehmen -->
             <div class="row featurette">
             <div class="col-md-6"><%= image_tag("bus.jpg", class:"featurette-image img-responsive center-block") %></div>
             <div class="col-md-6"> <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. <br><br>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est.</p></div>
             </div>
             <br><br>
        </div>
     </div>

     <div class="container" id="stimmen">
        <div class="container2">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="item active">
                <%= image_tag("backgroundV2.png", class:"img-responsive stimmen-img") %>
              <div class="container">
                <div class="carousel-caption">
                  <h1 id="quotes"><q><i>Unsere Gemeinschaft entsteht jeden Tag neu. Egal ob in Sportvereinen, den Narrenzünften, dem Seehasenfest, in den Gemeinden, bei sozialen Projekten, auf der Arbeit oder in der Nachbarschaft. Gemeinschaft kann nur vor Ort und aus Vielfalt entstehen.</i></q></h1>
                
                </div>
              </div>
            </div>
            <div class="item">
              <%= image_tag("backgroundV2.png", class:"img-responsive stimmen-img") %>
              <div class="container">
                <div class="carousel-caption">
                  <h1 id="quotes"><q><i>Unsere Gemeinschaft entsteht jeden Tag neu. Egal ob in Sportvereinen, den Narrenzünften, dem Seehasenfest, in den Gemeinden, bei sozialen Projekten, auf der Arbeit oder in der Nachbarschaft. Gemeinschaft kann nur vor Ort und aus Vielfalt entstehen.</i></q></h1>
                  
                </div>
              </div>
            </div>
            <div class="item">
              <%= image_tag("backgroundV2.png", class:"img-responsive stimmen-img") %>
              <div class="container">
                <div class="carousel-caption">
                 <h1 id="quotes"><q><i>Unsere Gemeinschaft entsteht jeden Tag neu. Egal ob in Sportvereinen, den Narrenzünften, dem Seehasenfest, in den Gemeinden, bei sozialen Projekten, auf der Arbeit oder in der Nachbarschaft. Gemeinschaft kann nur vor Ort und aus Vielfalt entstehen.</i></q></h1>
                </div>
              </div>
            </div>
          </div>
         <!--  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a> -->
          <!-- <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"> -->
            <!-- <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> -->
            <!-- <span class="sr-only">Next</span>
          </a> -->
        </div><!-- /carousel -->
    </div>
    </div>

    <div class="container" id="contact">
        <div class="container2">
    	<div id="few_contactform">
                 <br>
	    <h1>Kontakt</h1>
                 <br> <!-- ggf rausnehmen -->
	    <div><p><b><%= flash[:notice] %></b></p></div>
	    <%= form_tag("/static_pages/mail_sent") do %>  
	    <div class="row">
	          <div class="col-md-8">
	            <div class="form-group">
	              <%= label_tag :name, "Name" %>
	              <%= text_field_tag :name, nil, class: "form-control", placeholder: "Ihr Name", :required => true %>
	            </div>      
	            <div class="form-group">
	              <%= label_tag :email, "E-Mail Adresse" %>
	              <%= text_field_tag :email, nil, class: "form-control", placeholder: "Ihre E-Mail", :required => true %>
	            </div>
	            <div class="form-group">
	              <%= label_tag :message, "Nachricht" %>
	              <%= text_area_tag :message, nil, class: "form-control", placeholder: "Ihre Nachricht", :required => true %>
	            </div>    
                            <%= submit_tag "Abschicken", class: "btn btn-default" %>   
                            <% end %>  
	          </div>
                        <div class="col-md-4">
                            <h3>Sprechen Sie uns an!</h3><br>
                            <p id="contact_text">Haben Sie Fragen? Oder Lust mitzuwirken? Interessiert daran uns zu unterstützen? Dann schreiben Sie uns. Oder schauen Sie doch mal bei <a href="https://www.facebook.com/Fr%C3%BChlingserwachen-ZusammenLeben-1693781200867345/"><i class="fa fa-facebook"></i></a> vorbei!</p>
                        </div>
	   </div>    
      </div>
      </div>
    </div>

    <div class="container" id="partner">
        <div class="container2">
             <br>
    	<h1>Partner</h1>
             <br>
             <div class="row">
                 <div class="col-md-4"><%= image_tag("studentlounge.png", class:"img-responsive") %></div>
                 <div class="col-md-4"><%= image_tag("studentlounge.png", class:"img-responsive") %></div>
                 <div class="col-md-4"><%= image_tag("studentlounge.png", class:"img-responsive") %></div>
             </div>
        </div>
    </div>


       <!-- FOOTER -->
    <div class="container" id="footer">
        <hr class="featurette-divider">
        <div class="container2">
            <p id="impressum"><%= link_to "Impressum", static_pages_impressum_path %></p>
        </div>
    </div>